spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db.thewaterwallets.in:3306/watercanapp_stock_db
      username: prod_user
      password: prod_user
  flyway:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db.thewaterwallets.in:3306/watercanapp_stock_db
      username: prod_user
      password: prod_user